production:
  access_key_id: <%= ENV['S3_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_ACCESS_KEY'] %>
  bucket: 'dasredmine'
  region: 'eu-central-1'
  endpoint: 's3.eu-central-1.amazonaws.com'
  secure:
  private:
  expires:

development:
  access_key_id:
  secret_access_key:
  bucket:
  endpoint:
  secure:
  private:
  expires:
